name: resultify
description: A Dart package for result-oriented programming, providing Result<R, E> type with convenient methods for streamlined error handling.
version: 0.4.0
repository: https://github.com/intales/resultify

environment:
  sdk: ^3.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
